### ISSUE TITLE
Test are failing

### ISSUE THREAD

**Issue by salaboy** [shrinkwrap/shrinkwrap-springboot#8]
When I try to build the project I'm getting: 

should_create_valid_spring_boot_15war_archive(org.shrinkwrap.springboot.app.SpringBootTest)  Time elapsed: 12.059 sec  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: org.shrinkwrap.springboot.app.SpringBootTest expected <200> but was <404> within 10 seconds.
	at org.shrinkwrap.springboot.app.SpringBootTest.validateSpringBootArchive(SpringBootTest.java:90)
	at org.shrinkwrap.springboot.app.SpringBootTest.should_create_valid_spring_boot_15war_archive(SpringBootTest.java:69)

is there any requirement to run those tests?

**Comment by lordofthejars** [comment]
Try to increase the timeout to 30 seconds. To release the version I used mvn release plugin so tests run passes for sure.

**Comment by salaboy** [comment]
Where is the timeout defined?

**Comment by lordofthejars** [comment]
In test itself, see await command
